terraform apply ci fix

diff --git a/.github/workflows/terraform_apply.yml b/.github/workflows/terraform_apply.yml
--- a/.github/workflows/terraform_apply.yml
+++ b/.github/workflows/terraform_apply.yml
@@ -1,19 +1,19 @@
 name: "Terraform Apply"
 on:
-    workflow_dispatch:
-        inputs:
-            action:
-                description: "Select action type"
-                required: true
-                default: "apply"
-                type: choice
-                options:
-                    - apply
-                    - destroy
-            confirm:
-                description: "Are you sure you want to proceed with this action?"
-                required: true
-                type: string
+  workflow_dispatch:
+    inputs:
+        action:
+            description: "Select action type"
+            required: true
+            default: "apply"
+            type: choice
+            options:
+                - apply
+                - destroy
+        confirm:
+            description: "Are you sure you want to proceed with this action?"
+            required: true
+            type: string
 permissions:
     contents: read
     id-token: write
@@ -24,9 +24,13 @@ jobs:
         runs-on: ubuntu-latest
         steps:
             - name: Check word
-              run: |
-                if [[ "${{ github.event.inputs.confirm }}" != "yes" ]]; then
+              run: | #validate inputs for mismatch
+                if [[ "${{inputs.confirm}}" != "yes" ]]; then 
                   echo "Action cancelled by user. or use lowercase 'yes' to confirm."
+                  exit 1
+                fi
+                if [[ "${{inputs.action}}" != "apply" && "${{inputs.action}}" != "destroy" ]]; then
+                  echo "Invalid action type. Please select 'apply' or 'destroy'."
                   exit 1
                 fi
     authenticate-azure:
@@ -37,7 +41,7 @@ jobs:
             - name: Azure Login
               uses: azure/login@v3
               with:
-                client-id: ${{ secrets.AZURE_CLIENT_ID }}
+                client-id: ${{ secrets.AZURE_CLIENT_ID }} #OIDC Login with azure and service key creds
                 tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                 subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
@@ -45,6 +49,12 @@ jobs:
         name: "Terraform Apply"
         runs-on: ubuntu-latest
         needs: authenticate-azure
+        env:
+              ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+              ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+              ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+              ARM_USE_OIDC: true
+        if: inputs.action == 'apply'
         steps:
            
             - name: Set up Terraform
@@ -52,27 +62,15 @@ jobs:
 
             - name: Terraform Init
               run: terraform -chdir=azure-deploy init
-              env:
-                ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-                ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-                ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-                ARM_USE_OIDC: true
+            
 
             - name: Validate Terraform
               run: terraform -chdir=azure-deploy validate
-              env:
-                ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-                ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-                ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-                ARM_USE_OIDC: true
+           
 
             - name: Terraform Plan
-              run: terraform -chdir=azure-deploy plan
-              env:
-                ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-                ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-                ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-                ARM_USE_OIDC: true
+              run: terraform -chdir=azure-deploy plan -out=tfplan -var="public_key=${{secrets.SSH_PUBLIC_KEY }}" #nneed public key
+            
             - name: Upload Terraform Plan
               uses: actions/upload-artifact@v3
               with:
@@ -84,7 +82,7 @@ jobs:
         name: "Terraform Apply"
         runs-on: ubuntu-latest
         needs: terraform-plan
-        if: ${{ github.event.inputs.action == 'apply' }}
+        if: inputs.action == 'apply'
         steps:
 
             - name: checkout code
@@ -93,7 +91,7 @@ jobs:
             - name: Azure Login
               uses: azure/login@v3
               with:
-                client-id: ${{ secrets.AZURE_CLIENT_ID }}
+                client-id: ${{ secrets.AZURE_CLIENT_ID }} #OIDC Login with azure and service key creds
                 tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                 subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
             - name: Set up Terraform
@@ -115,7 +113,7 @@ jobs:
                 path: azure-deploy/tfplan
 
             - name: Terraform Apply
-              run: terraform -chdir=azure-deploy apply -var="public_key=${{secrets.AZURE_PUBLIC_KEY }}" -auto-approve #nneed public key
+              run: terraform -chdir=azure-deploy apply -var="public_key=${{secrets.SSH_PUBLIC_KEY }}" -auto-approve #nneed public key
               env:
                 ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                 ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
@@ -129,4 +127,58 @@ jobs:
                 ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                 ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                 ARM_USE_OIDC: true
-                
+    
+    destroy-plan:
+      name: "Terraform Destroy Plan"
+      runs-on: ubuntu-latest
+      if: inputs.action == 'destroy'
+      needs: authenticate-azure
+      env:
+            ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+            ARM_USE_OIDC: true
+      steps:
+          - name: Set up Terraform
+            uses: hashicorp/setup-terraform@v3
+          - name: Terraform Init
+            run: terraform -chdir=azure-deploy init
+          - name: Terraform Destroy Plan
+            run: terraform -chdir=azure-deploy plan -destroy -out=tfdestroyplan -var="public_key=${{secrets.SSH_PUBLIC_KEY }}" #nneed public key
+          - name: Upload Destroy Plan
+            uses: actions/upload-artifact@v3
+            with:
+              name: tfdestroyplan
+              path: azure-deploy/tfdestroyplan
+              retention-days: 1
+
+    destroy-apply:
+      name: "Terraform Destroy Apply"
+      runs-on: ubuntu-latest
+      if: inputs.action == 'destroy'
+      needs: destroy-plan
+      steps:
+          - name: checkout code
+            uses: actions/checkout@v3
+
+          - name: Azure Login
+            uses: azure/login@v3
+            with:
+              client-id: ${{ secrets.AZURE_CLIENT_ID }} #OIDC Login with azure and service key creds
+              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          - name: Set up Terraform
+            uses: hashicorp/setup-terraform@v3
+
+          - name: Terraform Init
+            run: terraform -chdir=azure-deploy init
+            env:
+              ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+              ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+              ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+              ARM_USE_OIDC: true
+
+          - name: Download Destroy Plan
+            uses: actions/download-artifact@v3
+            with:
+              name: tfdestroyplan
